Update env_template
iotaledger/node-docker-setup pull request #31
Opened 2023-10-11 11:32 UTC by TeeVeeEss

2023-10-16 09:18 UTC, Dr-Electron approved these changes

2023-10-16 09:41 UTC, Dr-Electron requested changes

2023-10-16 09:41 UTC, Dr-Electron commented on stardust/env_template
> +# The .env file is your personal configuration and is used by Docker.
We think we should keep the uncomment message, wdyt?
```suggestion
# The .env file is your personal configuration and is used by Docker.
# Uncomment and edit the lines to fit your needs
```

2023-10-16 09:41 UTC, Dr-Electron commented on stardust/env_template
> +# The .env file is your personal configuration and is used by Docker.
Btw if we apply this, you don't need to create another PR in the wiki, I will just import this file into the wiki

2023-10-22 18:51 UTC, Dr-Electron approved these changes

2023-10-22 20:41 UTC, muXxer approved these changes

2023-10-22 20:41 UTC, merged